apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jenkins-eks-cluster
  region: us-east-1

vpc:
  id: "vpc-08e75504079d0113d"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1c: { id: subnet-077ca525e6614250a }
      us-east-1b: { id: subnet-06d01d73975c02610 }
      us-east-1f: { id: subnet-043960468b941d800 }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    #labels: { role: builders }
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ssh: 
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    tags:
      Name: ng-db
